services:
  db:
    image:  mysql:9.0
    command: --local-infile=1;
    ports:
      - "${DB_PORT}:3306"
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Moscow
    volumes:
      - ./source_database:/var/lib/mysql
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

  app:
    build:
      dockerfile: Dockerfile.app
    depends_on:
      - db
    restart: always
    ports:
      - "${SERVER_ADDRESS}:8080"

volumes:
  source_database:
    driver: local
