basePath: /
definitions:
  domain.CakeDecoration:
    properties:
      amount:
        type: integer
      article:
        type: string
      costPrice:
        type: number
      image:
        type: string
      name:
        type: string
      supplier:
        $ref: '#/definitions/domain.Supplier'
      supplierName:
        type: string
      type:
        type: string
      unit:
        type: string
      weight:
        type: number
    type: object
  domain.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  domain.Ingredient:
    properties:
      amount:
        type: integer
      article:
        type: string
      costPrice:
        type: number
      gost:
        type: string
      image:
        type: string
      ingredientType:
        type: string
      name:
        type: string
      packing:
        type: string
      specs:
        type: string
      supplier:
        $ref: '#/definitions/domain.Supplier'
      supplierName:
        type: string
      unit:
        type: string
    type: object
  domain.Item:
    properties:
      name:
        type: string
      size:
        type: string
    type: object
  domain.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  domain.LoginResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      role:
        type: string
    type: object
  domain.Order:
    properties:
      assignedManager:
        $ref: '#/definitions/domain.User'
      assignedManagerName:
        type: string
      date:
        type: string
      examples:
        type: string
      expectedFulfilmentDate:
        type: string
      id:
        type: string
      item:
        $ref: '#/definitions/domain.Item'
      itemName:
        type: string
      name:
        type: string
      orderer:
        $ref: '#/definitions/domain.User'
      ordererName:
        type: string
      price:
        type: number
      status:
        type: string
    type: object
  domain.OrderRequest:
    properties:
      description:
        type: string
      examples:
        type: string
      id:
        type: string
      manager:
        type: string
      name:
        type: string
      orderer:
        type: string
      size:
        type: string
    type: object
  domain.RefreshTokenResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  domain.SignupRequest:
    properties:
      fullName:
        type: string
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  domain.SignupResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  domain.Supplier:
    properties:
      address:
        type: string
      deliveryTime:
        description: в часах
        type: integer
      name:
        type: string
    type: object
  domain.Tooling:
    properties:
      marking:
        type: string
      properties:
        type: string
      type:
        $ref: '#/definitions/domain.ToolingType'
      typeName:
        type: string
    type: object
  domain.ToolingRequest:
    properties:
      acquireTime:
        type: string
      amount:
        type: integer
      decayLevel:
        type: string
      description:
        type: string
      name:
        type: string
      supplier:
        $ref: '#/definitions/domain.Supplier'
      type:
        $ref: '#/definitions/domain.ToolingType'
    type: object
  domain.ToolingResponse:
    properties:
      age:
        type: integer
      amount:
        type: integer
      name:
        type: string
      type:
        type: string
    type: object
  domain.ToolingType:
    properties:
      name:
        type: string
    type: object
  domain.User:
    properties:
      fullName:
        type: string
      login:
        type: string
      password:
        type: string
      photoURL:
        type: string
      role:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Описание работы сервера
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /decoration/delete:
    delete:
      consumes:
      - application/text
      parameters:
      - description: Article of a cake decoration to be deleted
        in: body
        name: Article
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Delete a given cake decoration by its article
      tags:
      - Cake Decorations
  /decoration/edit:
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of cake decoration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.CakeDecoration'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.CakeDecoration'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Edit a given decoration
      tags:
      - Cake Decorations
  /decoration/get:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.CakeDecoration'
            type: array
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Get a list of all cake decorations
      tags:
      - Cake Decorations
  /ingredient/delete:
    delete:
      consumes:
      - application/text
      parameters:
      - description: Article of an ingredient to be deleted
        in: body
        name: Article
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Delete a given ingredient by its marking
      tags:
      - Ingredients
  /ingredient/edit:
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of ingredient
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.Ingredient'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Ingredient'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Edit a given ingredient
      tags:
      - Ingredients
  /ingredient/get:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Ingredient'
            type: array
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Get a list of all ingredients
      tags:
      - Ingredients
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Login of user
      tags:
      - Authorisation
  /order/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of order request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.OrderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Create a new order
      tags:
      - Orders
  /refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.RefreshTokenResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.RefreshTokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Refresh access token
      tags:
      - Tokens
  /signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.SignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SignupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Signup of clients
      tags:
      - Authorisation
  /tooling/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.ToolingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Tooling'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Create a new tooling
      tags:
      - Toolings
  /tooling/delete:
    delete:
      consumes:
      - application/text
      parameters:
      - description: ID of a tooling to be deleted
        in: body
        name: Tooling_ID
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Delete a tooling
      tags:
      - Toolings
  /tooling/edit:
    post:
      consumes:
      - application/json
      parameters:
      - description: scheme of login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.ToolingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Tooling'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Update a tooling
      tags:
      - Toolings
  /tooling/get:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.ToolingResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.ErrorResponse'
      summary: Get a list of all toolings
      tags:
      - Toolings
swagger: "2.0"
